[slogan-latest-release]
other = "En son sürüm: &nbsp; <b>{{ . }}</b>"


[back-to-home]
other = "← <b>Ana sayfaya</b> geri dönün"

[back-to-parent]
other = "← <b>{{ . }}</b> bölümüne geri dönün"


[menu-community]
other = "Bir Topluluğa Katılın"

[menu-source]
other = "Kaynak Kodu"

[downloads-heading]
other = "Sürümler"

[downloads-install-from-pkg-manager]
other = "Zig'i bir paket yöneticisinden de <a href=\"https://github.com/ziglang/zig/wiki/Install-Zig-from-a-Package-Manager\">yükleyebilirsiniz</a>."

[downloads-json]
other = "Bu sayfanın <a href=\"https://ziglang.org/download/index.json\">JSON sürümü</a> mevcuttur."

[downloads-minisig]
other = "Dosyalar, bu genel anahtarı kullanarak <a href=\"https://jedisct1.github.io/minisign/\">minisign</a> ile imzalanmıştır:"

[download-binary]
other = "Çalıştırılabilir Dosya"

[download-documentation]
other = "<a href=\"{{ . }}\">Dil Referansı</a>"

[download-filename]
other = "Dosya Adı"

[download-sig]
other = "İmza"

[download-kind]
other = "Tür"

[download-release-notes]
other = "<a href=\"{{ . }}\">Sürüm Notları</a>"

[download-size]
other = "Boyut"

[download-source]
other = "Kaynak"

[download-stdlib-docs]
other = "<a href=\"{{ . }}\">Standart Kütüphane Belgeleri</a> (deneysel)"

[footer-translation]
other = "Bu sayfa ayrıca aşağıdaki dillerde de mevcuttur"

[news-rss]
other = "Bu sayfa aynı zamanda bir <a href=\"https://ziglang.org/news/index.xml\">RSS beslemesi</a> olarak da mevcuttur."
