[slogan-latest-release]
other = "最新版本: &nbsp; <b>{{ . }}</b>"

[back-to-home]
other = "← 返回<b>主页</b>"

[back-to-parent]
other = "← 返回<b>{{ . }}</b>部分"

[menu-community]
other = "加入社区"

[menu-source]
other = "源代码"

[downloads-heading]
other = "发布版本"

[downloads-install-from-pkg-manager]
other = "你也可以<a href=\"https://github.com/ziglang/zig/wiki/Install-Zig-from-a-Package-Manager\">通过包管理器安装 Zig</a>"

[downloads-json]
other = "这是<a href=\"https://ziglang.org/download/index.json\">这个页面的 JSON 版本</a>"

[downloads-minisig]
other = "使用以下公钥通过 <a href=\"https://jedisct1.github.io/minisign/\">minisign</a> 对文件签名:"

[download-binary]
other = "二进制"

[download-documentation]
other = "<a href=\"{{ . }}\">语言参考</a>"

[download-filename]
other = "文件名"

[download-sig]
other = "签名"

[download-kind]
other = "文件类型"

[download-release-notes]
other = "<a href=\"{{ . }}\">发行说明</a>"

[download-size]
other = "文件大小"

[download-source]
other = "源代码"

[download-stdlib-docs]
other = "<a href=\"{{ . }}\">标准库文档</a>(实验性)"

[news-rss]
other = "此页面也可用作<a href=\"https://ziglang.org/news/index.xml\">RSS源</a>"
