name: Build Tarballs
on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:
    inputs:
      zig_release_tag:
        description: "zig tag to build"
        required: true
        type: string
        default: ""
      zig_bootstrap_branch:
        description: "zig-bootstrap branch to checkout"
        required: true
        type: string
        default: "master"
concurrency:
  group: tarball
jobs:
  create_tarballs:
    timeout-minutes: 560
    outputs:
      skipped: ${{ steps.build.outputs.skipped }}
    runs-on: [self-hosted, tarballs, x86_64]
    env: 
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ZIG_RELEASE_TAG: ${{ inputs.zig_release_tag }}
      ZIG_BOOTSTRAP_BRANCH: ${{ inputs.zig_bootstrap_branch }}
    steps:
      - name: Check out code
        with:
          ssh-key: ${{ secrets.TARBALL_COMMIT_SSH_KEY }}
        uses: actions/checkout@v2
      - name: Build Tarballs
        id: build
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: ./.github/workflows/build-tarballs.sh
