name: Deploy Website

on:
  workflow_call:
    inputs:
      ref:
        type: string
        required: true
  push:
    branches:
      - main
concurrency:
  group: website
jobs:
  build:
    name: Build
    runs-on: [self-hosted, website]
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          ref: "${{ inputs.ref }}"

      - name: Build the website
        run: |
          /home/ci/deps/zig-linux-x86_64-0.13.0/zig build --cache-dir /home/ci/actions-runner-website/_work/www.ziglang.org/zig-cache --summary new -p /var/www/html/
